// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-pages/BrutalistSignal.tsx": () => import("../components/mockups/landing-pages/BrutalistSignal.tsx"),
  "./components/mockups/landing-pages/CommandCenter.tsx": () => import("../components/mockups/landing-pages/CommandCenter.tsx"),
  "./components/mockups/landing-pages/EditorialMinimal.tsx": () => import("../components/mockups/landing-pages/EditorialMinimal.tsx"),
  "./components/mockups/landing-pages/SocialProofFirst.tsx": () => import("../components/mockups/landing-pages/SocialProofFirst.tsx")
};
